### ISSUE TITLE
App Release Checklist

### ISSUE THREAD

**Issue by rauhul** [HackIllinois/iOS#164]
# Checklist
## Cosmetics
- [ ] Day color palette
- [ ] Night color palette
- [ ] Images
- [ ] Lottie animations
- [ ] No auto-layout warnings
### Persistent Data
- [ ] Keychain stores login data
- [ ] Purge persistent data on logout
- [ ] Properly update events
- [ ] Properly update announcements
### Login/Logout
- [ ] Login
- [ ] Logout
- [ ] Keychain auto-login
### Home View
- [ ] Countdown times
- [ ] Upcoming Events
- [ ] Happening Now Events
### Schedule
- [ ] Properly update tableview on tab change
- [ ] Pull to refresh
- [ ] Favorite/Unfavorite
- [ ] Locations appear alphabetically
- [ ] Cells push to detail view

> TODO: finish list

**Comment by lasyaneti** [comment]
Outdated issue.
