### ISSUE TITLE
2020 App Release Checklist

### ISSUE THREAD

**Issue by PatrickKan** [HackIllinois/iOS#270]
# Checklist
## Cosmetics
- [x] Gradient Background
- [x] New App Icon
- [x] New iMessage Stickers and 
- [x] New Loading animation
- [x] Login Page UI
- [x] Remove MenuTabController from UI and shift UI upwards in screen
- [x] Update status bar color to be black on iOS 13 in dark mode
- [x] Update scanner view to fill whole view (remove top gradient)
## Home View
- [x] Home View Background (with clouds and building in proper place)
- [ ] Upcoming Events and Happening Now Events in one EventList view with separator OR shift buildings up
## Schedule
- [x] Event identification by ID
- [x] Pull to refresh
- [x] Favorite/Unfavorite
- [x] Modal popup for event detail
- [x] Redesigned event cells
- [x] Redesigned eventdetail view
## Projects
- [x] Project identification by ID
- [x] Pull to refresh
- [x] Favorite/Unfavorite
- [x] Modal popup for project detail
- [x] Redesigned project cells
- [x] Redesigned project detail view
- [x] Project cells tag labels (UICollectionView)
## Tab Bar
- [x] QR Code popup animation
- [x] QR Code button mapped to popup
- [x] Custom TabBar to switch views
## Indoor Maps
- [x] Make sure maps are correct color scheme and centered
## Event Scanner
- [x] Ensure scanners are only available for staff and admin roles in the Event Detail Page
- [x] Check in event has special scanner and endpoint
- [ ] Check in RSVP override is only available to admins
## Announcements
- [x] Update UI for announcement cells
- [x] Bell icon in top right of home view for Announcements
- [x] Query announcements by ID from API

> TODO: finish list

**Comment by PatrickKan** [comment]
@ashayp22 for your reference the 2020 checklist

**Comment by lasyaneti** [comment]
Outdated issue.
